In [1]:
%load_ext google.cloud.bigquery

In [2]:
%%bigquery
SELECT sess

,id,first_name,last_name,email,gender,ip_address
0,3,Monty,Fleetham,mfleetham2@arizona.edu,Male,58.143.211.76
1,19,Des,Busek,dbuseki@samsung.com,Male,152.57.103.100
2,26,Honor,Haig,hhaigp@columbia.edu,Male,63.251.17.75
3,45,Kittie,Cockerell,kcockerell18@ibm.com,Male,193.193.64.196
4,52,Rosana,Paolino,rpaolino1f@unblog.fr,Male,166.105.216.200
5,57,Marget,Wesley,mwesley1k@google.co.jp,Male,38.86.66.110
6,71,Blancha,Soreau,bsoreau1y@fda.gov,Male,79.11.86.171
7,73,Nikolaos,Ireland,nireland20@constantcontact.com,Male,114.5.51.196
8,77,Guillema,Ingilson,gingilson24@microsoft.com,Male,207.179.56.214
9,80,Talbert,De Fries,tdefries27@360.cn,Male,82.195.164.39